"""Public schema exports for JobPilot."""

from app.schemas.application import (
    ApplicationPack,
    EvidenceBackedStatement,
    FactCheckItem,
    FactCheckStatus,
    ResumeAdjustmentSuggestion,
)
from app.schemas.base import JobPilotBaseModel, JsonValue, NonEmptyStr
from app.schemas.candidate import (
    CandidateExperience,
    CandidateFact,
    CandidateProfile,
    CandidateSkill,
    CandidateSkillLevel,
    CertificationItem,
    EducationItem,
)
from app.schemas.common import ToolError, ToolWarning
from app.schemas.evidence import EvidenceConfidence, EvidenceItem, EvidenceSourceType
from app.schemas.job import (
    JobDetail,
    JobRequirement,
    JobRequirementType,
    JobSourceType,
    JobSummary,
    RequirementPriority,
)
from app.schemas.matching import FitReport, FitScoreBand, RequirementMatch, RequirementMatchStatus
from app.schemas.state import AgentMessage, AgentMessageRole, AgentState, AgentStatus
from app.schemas.tool_inputs import (
    FileExtension,
    GenerateApplicationPackInput,
    InspectProjectEvidenceInput,
    LoadCandidateProfileInput,
    LocalPathStr,
    ReadJobDetailInput,
    ScoreJobFitInput,
    ScoringWeights,
    SearchJobsInput,
)
from app.schemas.tool_outputs import (
    CandidateProfileResult,
    CandidateProfileSuccess,
    EvidenceScanResult,
    EvidenceScanSuccess,
    GenerateApplicationPackResult,
    JobSearchResult,
    JobSearchSuccess,
    ReadJobDetailResult,
    ScoreJobFitResult,
    ToolFailure,
)

__all__ = [
    "AgentMessage",
    "AgentMessageRole",
    "AgentState",
    "AgentStatus",
    "ApplicationPack",
    "CandidateExperience",
    "CandidateFact",
    "CandidateProfile",
    "CandidateSkill",
    "CandidateSkillLevel",
    "CertificationItem",
    "EducationItem",
    "EvidenceBackedStatement",
    "EvidenceConfidence",
    "EvidenceItem",
    "EvidenceSourceType",
    "EvidenceScanResult",
    "EvidenceScanSuccess",
    "FileExtension",
    "FactCheckItem",
    "FactCheckStatus",
    "FitReport",
    "FitScoreBand",
    "GenerateApplicationPackInput",
    "GenerateApplicationPackResult",
    "InspectProjectEvidenceInput",
    "JobDetail",
    "JobPilotBaseModel",
    "JobRequirement",
    "JobRequirementType",
    "JobSourceType",
    "JobSummary",
    "JobSearchResult",
    "JobSearchSuccess",
    "JsonValue",
    "LoadCandidateProfileInput",
    "LocalPathStr",
    "NonEmptyStr",
    "ReadJobDetailInput",
    "ReadJobDetailResult",
    "RequirementMatch",
    "RequirementMatchStatus",
    "RequirementPriority",
    "ResumeAdjustmentSuggestion",
    "ScoreJobFitInput",
    "ScoreJobFitResult",
    "ScoringWeights",
    "SearchJobsInput",
    "ToolError",
    "ToolFailure",
    "ToolWarning",
    "CandidateProfileResult",
    "CandidateProfileSuccess",
]
